Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-25.10"
  config.vm.box_check_update = false

  # TODO() Doesn't work need VPN?
  # require plugin https://github.com/leighmcculloch/vagrant-docker-compose
  #config.vagrant.plugins = "vagrant-docker-compose"

  # install docker and docker-compose
  #config.vm.provision :docker
  #config.vm.provision :docker_compose

  config.vm.provider "virtualbox" do |vb|
    # имя виртуальной машины
    vb.name = "ubuntu-25.10-test"
    # объем оперативной памяти
    vb.memory = 2048
    # количество ядер процессора
    vb.cpus = 2
  end
  
  # hostname виртуальной машины
  config.vm.hostname = "ubuntu-25.10-test"
  config.vm.network "public_network" # select wifi
    #config.vm.network "private_network", type: "dhcp"  # Failed at start

  # TODO() Export ports
#   config.vm.network "forwarded_port", guest: 8082, host: 8080
#   config.vm.network "forwarded_port", guest: 3909, host: 3909
end