Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-25.10"
  config.vm.box_check_update = false

  # Fix some git troubles
  config.vm.synced_folder ".", "/home/vagrant/code"

  config.vm.provision "shell", inline: <<-SHELL
    echo "none /tmp tmpfs size=2G 0 0" >> /etc/fstab
    mount -o remount /tmp

    # Install packages
    sudo apt update
    sudo apt install -y docker.io net-tools qemu-user default-jre awscli tmux
    sudo usermod -aG docker $USER
  SHELL

  config.vm.provider "virtualbox" do |vb|
    # имя виртуальной машины
    vb.name = "ubuntu-25.10-test"
    # объем оперативной памяти
    vb.memory = 2048
    # количество ядер процессора
    vb.cpus = 4
  end
  
  # hostname виртуальной машины
  config.vm.hostname = "ubuntu-25.10-test"

  # Warning! Edit by hand for own interface
  config.vm.network "public_network", bridge: "wlp82s0"
end